version: '3.8'

services:
  proxy:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./data:/sites/app
  db:
    image: postgres:14-alpine3.14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: ./backend
    command: sh -c './wait-for db:5432 -- dotnet API.dll'
    environment:
      DATABASE_URL: 'Server=db; Port=5432; User Id=postgres; Password=postgres; Database=postgres'
    depends_on:
      - db
  adminpanel:
    build: ./adminpanel
    ports:
      - 3000:3000
    volumes:
      - ./adminpanel:/app
    environment:
      REACT_APP_DOMAIN_API: 'devapp.test'
  frontend:
    build: ./frontend
    ports:
      - 4000:4000
    volumes:
      - ./frontend:/home/node
