name: deploy-adminpanel

on:
  push:
    branches: [ master ]
    paths: ['adminpanel/**']
  workflow_dispatch: 

jobs:

  build_and_push:
    name: Build React app and push files to DO droplet
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Build React app
      working-directory: ./adminpanel
      run: |
        npm install
        npm run build
    
#     - name: Copy file via ssh password
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.DO_HOST }}
#         username: ${{ secrets.DO_USERNAME }}
#         password: ${{ secrets.DO_PASSWORD }}
#         port: 22
#         source: "adminpanel/build/**"
#         target: "project/data/adminpanel/"

    
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: adminpanel/build
        remote: project/data/adminpanel
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        rmRemote: true


    
